spring:
  profiles: alpha
  message: Hello Spring ContentsService Alpha Server!!!!!
spring:
  profiles: local
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true