spring:
  profiles: alpha
zuul:
  routes:
    member:
      stripPrefix: false
      path: /v1/member/**
      url: http://localhost:8082
    pay:
      stripPrefix: false
      path: /v1/pay/**
      url: http://localhost:8083
    else:
      stripPrefix: false
      path: /v1/**
      url: http://localhost:8083
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true      