spring:
  profiles: local
zuul:
  routes:
    member:
      stripPrefix: false
      path: /v1/member/**
      serviceId: member-service
    pay:
      stripPrefix: false
      path: /v1/pay/**
      serviceId: contents-service
    else:
      stripPrefix: false
      path: /v1/**
      serviceId: contents-service