spring:
  profiles: local
zuul:
  routes:
    member:
      stripPrefix: false
      path: /v1/member/**
      url: http://localhost:8082
    pay:
      stripPrefix: false
      path: /v1/pay/**
      url: http://localhost:8083
    else:
      stripPrefix: false
      path: /v1/**
      url: http://localhost:8083